services:
  - type: private-service
    name: mysql-db
    runtime: docker
    repo: https://github.com/mahamad5ahmad/DigiMates-Backend-3EmployeeManagementSystem
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_DATABASE
        value: mydb
      - key: MYSQL_USER
        value: myuser
      - key: MYSQL_PASSWORD
        value: mypassword
      - key: MYSQL_ROOT_PASSWORD
        value: rootpassword
    plan: starter
